#+TITLE: The Only Page
#+OPTIONS: timestamp:nil toc:nil author:nil num:nil ^:nil
#+LANGUAGE: en
* *Intro*

This is a minimalist page, so be sure that you are using a browser that is also minimalist enough :-D
  Happy viewing. Written in Emacs, BTW

#+TOC: headlines 2

      
* *FEATURES*

This page can be viewed:

+ without javascript enabled, there is none
+ without image support
+ with any font you like, it should not break the page beyond legibility
+ even on a dumbphone (but you know that from these previous points, right?)
  
* *What I like, do and stuff*

   - Born in Slovakia, 1984, currently living in Prague, CZ
   - I like computers, hamradio, fountain pens, open source
   - Working as a technical support for an adult entertainment website
   - Emacs Enthusiast (more about that lower)
   - Using +openSuse+ and +Fedora+ wherever I can, BSDs even where I can't - UPDATE: I somehow lean towards Ubuntu more and more.
   - GNU Guix fan, but noobie
   - orgmode user, wrote the whole page here
   - name is obviously "Peter Kotrčka" :-D


* *Photography*

I am not the greatest photographer in the world, but it is one of my passions.
Mostly I am using my phone, like every sane person on this planet maybe, but film photography is one of my "offline" hobbies.
When I revisited my camera collection just a few days ago, I have found that currently I am a rangefinder exclusive photographer (in 35 mm format).

Here is a list of cameras I own:

+ unspecified number of Kiev 4 cameras (most likely 3 pieces, if there is no other hidden somewhere) + some Jupiter 8 lenses

+ Leotax -f-

+ Canon 7, unknown model, I do not use that one as much as I would love to because of a pretty dull and hazy rangefinder patch

+ Voigtländer Bessa L

+ Zorki 4

Also, I have a TLR, Yashica D (the one with 3,5 lens), a lovely but not really compact camera and then an unspecified Zeiss Ikon folding camera from 1930's.

Every single camera is in working order (more or less), I got rid of my non working cameras and still have plenty of machines to use.

As for lenses, a bunch of soviel L39 (Leica screw mount) lenses like Jupiter, Industar, the obvious and commonly available stuff.

This article will have an update, I just need to think about what and how I would like to share more details about these cameras.
Because, it would probably be more beneficial for you to see them and / or to see the output (images).

* *Computer Stuff*


** *Emacs*

*** *Why?*

I was a fan of simply solutions for a quite long time. So why would I change that for Emacs?
Well, as many emacs haters will tell you, Emacs is more of an operating system rathern than
text editor. Which is correct, if you do nto have any multmedia ambitions on your computer,
you can do almost everything inside Emacs. It has a huge advantage, usually the same keyboard
shortcuts (bindings) for every "program" inside Emacs. It is the same as for vim users when
they are so so so so much happy about vim key bindings in various terminal programs like
ranger, ...

This is just the beginning of my path, I am only using a few things inside Emacs because
it is very easy to get overwhelmed by so many possibilities. And I would like to do it slightly
different this time, take smaller chunks and go deeper rather than cover everything at once
and nothing well or deep enough. So my first steps are:

- work inside every buffer efficiently, know my key bindings

- setup a few, most used packages and practise by really using them (elfeed, mastodon, dired)

*** *Vanilla?*

Yes, I'm using a vanilla Emacs, no vim key bindings no distributions. I mean, there's nothing
wrong with using Emacs distributions, especially when you want to see what is possible to do
inside Emacs, but a lot of them are just packing a looooot of stuff for programming, so many
different packages. And I have found that I can do a lot of things even without these packages
just because Emacs does everything right :-D Please repeat, Emacs does everything right.

But if I would have to recommend a package, it would be a "vanilla Emacs keybindings" one
like Prelude or Centaur (use [[https://lite.qwant.com][search engine]] to find out more), those seem like well themed,
curated and actively developed Emacs distros.

*** *Theming*

Oh yes, this is important, you need to have a beautiful theme to be able to promote your stuff on
#emacsporn or #unixporn on reddit, right? Oh yes you need. So, as you can find later on this page,
there is a link to a cool greek guy who created a light and dark theme, from which I am using
the light one during the day. Otherwise, just select the "Wombat" one, it is preinstalled and
you will be as happy as I am.

OK, for now, "Leuven" (light theme) it is


*** *I need more info, now*

OK, if this is not enough, visit:

- [[https://protesilaos.com][Protesilaos Stavrou]] and his page, youtube channel, etc.
- System Crafters (again, use search engine to find out the youtube channel)
- [[https://sachachua.com][Sacha Chua]] website for weekly news and other sources


** *+Lenovo+ IBM Plex*

I like to use +Lenovo+ IBM Plex font wherever I can. You can find it in your repo (OpenBSD has it, NetBSD has it, Debian has it, for the rest - use your favourite.. no, use this search engine - [[https://metager.org][click]] to find and download it).


* *Kurrent*

** *What is Kurrent?*

  Kurrent is an old german handwritten script, used primarily prior 1940s when it was banned by the Nazi government. There are multiple variants of this script, the most modern one called Sütterlin.
  There are some slight differences between these variants, however - once you know one of these variants, it is a matter of minutes to pick up those 3-4 characters written in some different way.

** *Why Kurrent?*

    Well, that's a good question. There are not that many use cases, especially when you are an enaglish language native speaker and / or don't know that much of a German. Of course, there are a plenty of materials written in other languages by using this script, but still - tha majority of it is in German.
    For me, it is a good way how to motivete myself to actually learn a bit more German and also to practise handwriting, since I'am also a fountain pen fan. Some of my penfriends are from Germany and (actually to all of them) I'm writing letters to them in Kurrent. In english, so far, but still, at least something, step by step.

** *How Kurrent?*

  There are many materials online on how to learn to write and read Kurrent, a lot of scans of older cookbooks, letters, postcards - so if you are interested, just Metager (or Google, if you must) "kurrent" and you are good to go, learning materials will be on top of your search results. There are also some Facebook groups dedicated to Kurrent / Sütterlin and people there are really welcoming, even if you don't speak German.

** *Conclusion*

  Kurrent is my only other (than Latin) script I know, so it is maybe a bit too early to say this, but I like it very much. It slows me down, I can enjoy writing in it a bit more, it opens new gates to german language, german culture, german history. And actually, learning it was an easy process, just a matter of a day or two. Practising Kurrent handwriting is a never ending process, but still, very enjoyable.
  
** *Resources*

  [[http://www.kurrent-lernen-muecke.de/][Margarete Mücke Kurrent Seite]]

  [[https://www.youtube.com/watch?v=1AgE_4P0cSs][Kurrent writing course - Youtube video (3 hrs)]]

  ... more will be added later

* *German language*

My kryptonite. I wasn't able to learn this language or progress further than to the level where I can watch a youtube video of some kind of an
influencer and get an idea what it is all about. Which, lets be honest, is not a very high level, right? I wanted to improve my language
skilly by using german in my letters to penfriends (in combination with Kurrent), but it is not enough. If you are reading this page and
also if you are learning german, let me know what could help. Duolingo is not working for me either.

December 2022 update: not much of a change, but I feel like I understand a little bit more, even IRL in Germany. 

** *Auf Deutsch*

Hallo, mein name ist Peter und ich schreibe diesen bereich meiner Website in deutscher Sprache. Oder in einer Sprache, die dem Deutschen irgendwie ähnelt.
Die deutsche Sprache is mein Kryptonit, merh also "Hallo" sagen kann ich nicht lernen. Hilfe, bitte :-(

* *Random notes from my life*

** *2021*

*** *May 9* - edited [[http://pkotrcka.inlisp.org/emacs.html][emacs.html]] page as a practise in editing inside Emacs. I also updated
my RSS feed sources, got rid of reddit junk (or at least the most of it) and put some lower
traffic, but interested sources

*** *May 9* - making a short video about my workflow in #Emacs. And as usual, I can nto type when I
also record my video :D This is a document made in *org* which will be exported to HTML and uploaded to my
FTP. Nothing fancy, nothing special, maybe I will add a link to something like Alex's blog. Alex Schroeder is
another Emacs enthusiast, so why not? Here it is: [[https://alexschroeder.ch][Alex's page]] 

OK, now I have to find a way how to use ffmpeg and make this video faster (speed up). So we will use eww, of
course :D Maybe I have found it, it shoult work like this:

#+BEGIN_SRC shell
ffmpeg -i input.mkv -filter:v "setpts=0.5*PTS" output.mkv
#+END_SRC


Hmmm, should I put the code into the code section? Let's see if I could use org mode help here.
I was able to do that, nice :-D And now, export the document and upload it onto FTP.

*** *June 5*

On my path to find a better web browser, I am back on Vivaldi. As you may already know, I have a few computers, some of them are powerful enough not to show off the lack of speed when using Firefox.

But I also have a underpowered UMAX laptop which shows this pretty happily. So my quest was, to find if there is a greener grass on the Chromium part of the garden. And it seems there is.

I used Vivaldi and yes yes yes, there is a significant speed increase. Probably it will be worse with RAM usage, but that I can live with.

I know that my ideal web browser would be Iridium, however - those german guys are not that regular with updates, also there are multiple versions for different Linux branches / distributions and each one of them is based on a different version.

Not to mention unresolved dependencies on my current distro. Yes yes, it is open source, I can bouild it - but can you imagine building it on this kind of laptop? :-D

*** *July 4*

Not a Independence day themed post.

However, still something to celebrate. I have a new computer, I decided to go for a secondary laptop since I will spend a lot of time at the office during the night.

And I miss having an UNIX system available with everything ready and installed for my needs. Of course, there is SDF, but still, own HW is own HW.

There was a small and unexpected surprise when I bought a laptop that was my first choice. ASUS ExpertBook, 14", no Windows, yes RJ-45, FullHD display, good price. However, 
I like to use Emacs as my editor of choice (and for other things as well) and guess what. I was so lucky with my first laptop (HP x360) where keyboard rollover was functioning as
expected, that I was not expecting it to be different on any other laptop. But it is. And not like "ASUS has it, HP not", it is different, model after model. It might look similar but the
keyboard behaves completely different. So, it went back and I spent my sunday afternoon by trying (lucky for me, I was able to test this) laptops that are within my budget, have a 
decent keyboard with working rollover, have non-qualcomm wifi, etc. And tadaaaa, the winner is ASUS again, something with tiger lake i5 (I would like to try an AMD laptop, but those are
still rare), 8 GB of RAM, some SSD inside. And I like it. maybe even a bit more than my HP, so I am not really sure which one will accompany me at the office. I wanted to leave the 
better machine at home, but now it might be this ASUS (yes, I already installed #emacs and typing this on this laptop).

Fedora works there like a charm - again, maybe even better than the HP with a slightly older chipset. I was a bit worried about the smaller touchpad but it is a good one, so
no problems here.

I will update :-)

*July 30*

On my other laptop that I left at work I installed the latest devel version of Ubuntu, Impish Indri. It was my only chance since I only have had one USB drive with me. 
So if that would not work, I would be screwed. But it worked. It has its own flaws, of course, it is still 3 months away from release, but it works. And what I need?
Simple, Emacs, Vivaldi (yeah, will explain later), some video player and a system base taht will not crash just like that. And for that, Ubuntu devel in the middle of the
development cycle is more than enough.

This, of course, was written on that very system :-D

*** *August 1*

For the first two weeks, my new ASUS laptop was more of a testing platfomr, I always like to try what is possible, what works and what does not.
What a surprise was that I have found Ubuntu is not possible to install (at least not by deafult) because it can not see the internal drive.
That's 21.04, of course, but I am not a lazy guy so I tested a release that will become 21.10 one day and all fo the sudden, it sees the drive and works correctly.
Not sure what happened, maybe a kernel version bump (5.11 in stable, 5.13 in the future release), maybe something else. But everything works.

So far so good - Fedora works, Ubuntu (will) works, openSuse Tumbleweed works. Manjaro works, but... Yes, there is still some but(t), it has other issues, which are
probably not HW related.

Hey, maybe you would like to actually know what laptop it is - so the model name is Asus X415EA-EB037T (probably a local variant, but in any case - Tiger Lake i5 CPU,
8/256 RAM/storage). I know that it is not a super expensive laptop, but I really like it. I know, I know, you will tell me that the display is terrible (yes, there are 
slight light leaks here and there when the backlight is turned high), the keyboard is terrible (it is not, I Like typing on it and it even has T shaped arrow keys layout 
(but yes, still half height, but at least something). Sound is OK, I can not really comapre it to the HP which has front facing speakers above keyboard, but at least the 
sound output into headphones is very decent.

I am not sure about the battery life, all of my laptops are actually more of a desktop replacement with a tiny footprint :-D so... But, I would guess 5+ hours with
an average load, amybe a bit more with "content consuming". What I Like, on the other hand is the fact that it is quiet, yet still cool. My HP crank up fans very quickly 
when there is a CPU load and it is pretty loud. ASUS keeps it quiet for a much much longer time.

So overall, I am happy, I typed a lot of text on this laptop, listened to a good music, watched some videos, everything works as expected. I know that it is a bit too
early for recommendation, but so far, so good.

** *2022*

*** *February 5, 2022*

New Year, new adventures. So, what am I going to do this year?

A few resolutions like less coffee, more quality coffee, less GAS (gear acquisition syndrome) and impulse purchases. That's normal and I will probably break those within a few months.

Then, I would like to get my german into the "conversational" level, more than just the "hardly able to say hello" level I am stuck on for years.

Also, I would love to learn something useful on computers. Programming always fascinated me and it would not be that hard to learn (I think) but I also know, what is probably the biggest issue.
I do not have any project I could do long term that would grow with me, has a meaning, ...
Os instead of that, I could just try to learn to script, shell script. That is something I could then use on a daily basis. This needs more thinking and you'll be updated.

Of course, less social media.. right?

*** *April 24*

Somehow, all that war and everything got me, 2 months after the start. Two years of COVID and now this. Poor people in Ukraine, prices of everything skyrocketed, Russia is still an idiocracy.
That's not good, not good at all. What I' mtrying now is taht I will avoid news sites, if that helps my mood a bit. I will also start night shifts again, so I'll try to focus on programming and
learning some new computer stuff.

*** *May 11*

Updated my [[http://pkotrcka.inlisp.org/index.html][main page]] to include almost everything that is possible to put on one page, the only exception is this notepad. And I like it, it is really readable even on a phone. It's not for people that like
videos or such, but rather for someone who likes to read a little bit. I will add even more stuff later in the late 90s fashion - html in its best :-D 

*** *May 13*

Removed the "What I do not like" section, started to type about NetBSD and also added somwthing about german language. We are getting there.

*** *May 14*

I have created a new Youtube channel for my adventures with computers. As an Emacs user
I have selected a name that is very appropriate - AmateurVimer :-D Content is really
easy to create and it seems to be fun. Will see how I will feel about it later on.

*** *June 1*

A lot has happened. I deleted this page, started to create a new one, also changed my mastodon instance.
Then I have found this copy of the page on my laptop so re-decided to edit this stuff and give it another try.
My roommate will leave, that means much more space in the apartment but also a higher rent :-(
I am so much behind my penpals letter writing, I *have to* do something about it.
It's been three months since I wrote an article about the laptop I'm using right now and it hasn't been published yet.
I wonder if it ever gets published.

*** *August 24*

Nothing much has happened, I was on my holiday in Germany. It was nice, I will miss that.

*** *December 10*

I have restarted my phlog on gopher. Not sure how that will end, that's a problem of the future Peter :-D Also, I am doing our social media in the company partially again.
I won't lie, it is partially about the money, but most of it, maybe 70% - I need to do something else than my regular job just to be able to stay in this company.
And I'm waiting for something to come up that will be a new challenge for me, something creative (which, to be honest, this social media is NOT). We'll see what it'll become.

** *2023*

*** *January 3*

Happy New Year everyone, I actually remembered to update this page early on, so.. New Year resolutions? More Emacs for me, maybe some scripting and someone on Mastodon told me to
look into LaTeX, so.. If I'm going to publish my silly beer and coffee newspapers for my colleagues, that could be useful.
And of course, eatl more healthy, less sugar, less garbage food, ...

*** *January 7*

I have updated the Programming section, added some resolutions for 2023 there. Installed Fedora Rawhide on my spare work laptop, we'll see how it'll hold up.
I wanted to record a second episode of my beer podcast, to have at least a few episodes before I will star a channel or podcast itself but Audacity froze the whole computer.
Not sure, how, don't ask me, but it stopped after 7 minutes and nothing was saved. Honestly, it wasn't my best attempt anyway, but.. still, so much time wasted.
I bought a train ticket to Germany, Freiberg. You probably do not know the city, it is among smaller ones, but there is a brewery with probably the best Kellerbier I have ever tried.
It is possible to buy that beer in Dresden as well, but.. I want to see if the place of origin is the best place to drink such a special beer.
And I like trains, this will be another trip with Deutsche Bahn (from Dresden to Freiberg) and České dráhy (Prague -> Dresden). I am thinking about creating a dedicated train photo
Instagram account. I love trains, so why now? I know there are dedicated Mastodon instances for train enthusiasts as well, but IG should be a starting point. And from there, we'll see.

*** *January 31*

It was a pretty decent January. I was on a few trips, Germany again, of course. A lot of good beer, a lot of nice experiences. Not something I need to elaborate too much,
but yeah - a decent January. Now I am back on night shifts, so maybe the February will be more about learning new stuff. Still not sure what that will be. But I'll update you.

*** *February 4*

Pissed that my ISP / mobile services provider screwed my bill again, I have to go there AGAIN and describe all about my discounts and everything.
Plus, they have increased prices by 9%, so I am thinking about saying goodbye to them. There are other options available. Maybe a little bit less comfortable, but still.
As for this page, I removed a lot of stuff that is not relevant anymore, to clean the page a bit. I think you won't miss them, it was just a bloat.

*** *February 20*

Updates: deleted my Google account completely, switched to Huawei phone (no need of Google account there), FEB-21 will be my mobile services provider switch.
Moved to neocities because for some reason, sdf revoked my ftp access.

*** *February 25*

Mobile services provides changed successfully. For some reason, I am unable to access FTP on SDF so I neede to change my webhosting.
Sadly, the most convenient service that allows hosting my html as well as org files is github. So I have a website there :-(
I am not happy about it, but that's the way it is for now. BTW, I already have a follower on guthub. Not sure who and why. Mostly why.
On Sunday, February 26, I will go for a beer degustation again. We need (me and my colleague) to try some new beers and have a discussion
about them.
During the night, I was trying to compile and config FVWM3. Compilation was super easy, configuration was not. I was able to achieve some
things, but then I realized that all I wanted to create was another ratpoison, so I went back to ratpoison :-D
Added some new key bindings to it, so that might help using it on this poor laptop with more ease.

*** *March 5*

Not that much happening right now as I am stuck at work. I did manage to do a German visit early in the month, so now I can plan my future
trips much better. My new colleaue might take all those night shifts, so there is a slight chance of me being a daily guy again :-D
But of course, I am trying to be realistic about it and wait for the actual result.

*** *March 15*

I have changed my emacs theme to ef-themes (by Prot) in the Autumn colors, pretty nice and warm tones, earthy. Pleasant to look at.

*** *March 19*

I made a lot of videos about Emacs. Not sure if that will be something regular, but so far - I like doing that.

* *Contacts*

Electronic mail: pkotrcka (at) vivaldi (dot) net

Mastodon: @peterkotrcka@nrw.social

*Modified - March 19, 2023* - last mod: blog
